
title: <h4 style="color:White;"> port·fo·li·o /pôrtˈfōlēˌō/ noun \n 1. a large, thin, flat case for loose sheets of paper such as drawings or maps. 2. a range of investments held by a person or organization. 3. an employment pattern that involves a succession of short-term contracts and part-time work. "portfolio careers allow a person to balance work with family" </h4>
theme: jekyll-theme-cayman
